family.oamt$fam.str<-as.factor(family.oamt$fam.str)
> family.oamt$fam.city<-as.factor(family.oamt$fam.city)
> family.oamt$money.charged<-as.factor(family.oamt$money.charged)
> family.oamt$house.type<-as.factor(family.oamt$house.type)
> family.oamt$garage<-as.factor(family.oamt$garage)
> family.oamt$other.room<-as.factor(family.oamt$other.room)
> family.oamt$pet<-as.factor(family.oamt$pet)
> family.oamt$howdealrestfood<-as.factor(family.oamt$howdealrestfood)
> family.oamt$dinner.time<-as.factor(family.oamt$dinner.time)
> family.oamt$child.first<-as.factor(family.oamt$child.first)
> family.oamt$wine<-as.factor(family.oamt$wine)
> family.oamt$drink<-as.factor(family.oamt$drink)
> family.oamt$fruit<-as.factor(family.oamt$fruit)
> family.oamt$other.food<-as.factor(family.oamt$other.food)
> family.oamt$midnight.snack<-as.factor(family.oamt$midnight.snack)
> 